Card qat 1142 sign up
wolox-training/em-karate pull request #2
Opened 2020-10-05 22:17 UTC by Elvis-Mieles

## summary
The critical route of registering as a new user in the system is automated based on the CAR QAT 1142 Sign Up, acceptance criteria

2020-10-06 11:45 UTC, jmzagowolox requested changes

2020-10-06 11:45 UTC, jmzagowolox commented on src/test/java/training/sign_up/SignUp.java
> +    }
don't generate a report in every runner that you create. This code and this report must be in a general runner which execute all the features (in the future)

2020-10-06 11:45 UTC, jmzagowolox commented on src/test/java/karate-config.js
>    }
delete this logic if you won't use

2020-10-06 11:45 UTC, jmzagowolox commented on src/test/java/karate-config.js
>    }
good work with that! BUT we must not commit this data to the repository. Try to move this to a _.properties_ or _.env_ or whatever and don't push it.

2020-10-06 11:45 UTC, jmzagowolox commented on src/test/java/training/sign_up/json/successfulregistrationresponse.json
> +}
please add a space line to the end of the file.

2020-10-06 11:45 UTC, jmzagowolox commented on src/test/java/training/sign_up/sign_up.feature
> +    * assert /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(register.user.email)
why do you validate this data here? this data will be set by the environment, you don't need to validate it.

2020-10-06 11:45 UTC, jmzagowolox commented on src/test/java/training/sign_up/sign_up.feature
> +    * def password = register.password
think about in the running of the tests. If you set a specific user to run this feature, you will need to modify the karate-config file to run the test every time. Try to generate a random mail in order to won't have this problem.

2020-10-06 11:47 UTC, jmzagowolox commented
good work! In the follow branches don't put the card on the name of the branch, that's not necessary :).

2020-10-06 11:48 UTC, jmzagowolox requested changes

2020-10-06 11:48 UTC, jmzagowolox commented on src/test/java/training/sign_up/sign_up.feature
> +  Scenario: Register successfully
I recommend you use a Outline Scenario for this feature to validate all the tests cases :).

2020-10-06 15:17 UTC, Elvis-Mieles commented
## summary
The corrections listed above are made.

It is eliminated from the report to apply it when the tests are finished automating.

2020-10-06 19:06 UTC, Elvis-Mieles commented
##summary

The .properties is changed to a .json and the Sign Up scenarios are reduced

2020-10-06 20:29 UTC, Elvis-Mieles commented
## summary

the karate-properties.json file is modified

2020-10-07 03:16 UTC, Elvis-Mieles commented
## summary
Asserts are added to the feature sing up scenarios

2020-10-07 13:49 UTC, Elvis-Mieles commented
## summary
the response json validation is performed in the UnitTest scenario

2020-10-07 14:01 UTC, jmzagowolox approved these changes
Great job! 🙌

2020-10-07 14:02 UTC, merged