The task of creating, deleting and modifying article is performed
wolox-training/em-karate pull request #5
Opened 2020-10-08 15:51 UTC by Elvis-Mieles

## summarry
The task of creating, deleting and modifying article is performed

2020-10-08 16:17 UTC, jmzagowolox requested changes

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/article.feature
> +
please, delete this space line

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/responsesuccessfully.json
> +      "image": "https://static.productionready.io/images/smiley-cyrus.jpg",
is this ok? has all the articles the same image?

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +
please add a line in the end of the file

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/article.feature
> +    And match response.article.author.username contains username
that is the same creation you use on creation.feature. Please abstract this logic to one place

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/article.feature
> +
I would like to validate the updates doing a get on articles in order to know what data was really saved.

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/article.feature
> +    Then status <statusCode>
if you want to know if the article was really deleted, you have to do a get with it and check that the answer will be `404 - Not found`

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * print response
please delete the print

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    Given path 'articles', 'training-de-dllo-36xhmh'
you don't have to harcode the slug, you must to get a random one and do the changes with that.

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/create.feature
> +  @createSuccessfully
remember what we talked about the tags. You must to keep a logic on the names and add other names if you have multiples scenarios in a feature and you want to run only one.

2020-10-08 16:17 UTC, jmzagowolox commented on src/test/java/training/article/create.feature
> +
please, delete this space line

2020-10-08 19:35 UTC, Elvis-Mieles commented
##summary
The slug is changed to run automatically and not manually

2020-10-08 19:42 UTC, Elvis-Mieles commented
##summary

Update feature is updatedArticle

2020-10-08 20:20 UTC, jmzagowolox requested changes

2020-10-08 20:20 UTC, jmzagowolox commented on src/test/java/training/article/create.feature
> +      | Training de Dllo      |Studying Node js  |Training              |200       |
add a space line to the end of the file

2020-10-08 20:20 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def create = call read('create.feature@flow')
do a GET of all the articles and after that get a random slug of this response to update.

2020-10-08 20:20 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def create = call read('create.feature@flow')
1. GET of all articles. (it returns an array)
2. choose a random article.
3. Do the update (PUT).
4. GET that article.
5. Match responses between steps 3 and 4.

2020-10-08 20:20 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    And match response.article.author.username contains username
abstract this GET to a new feature file.

2020-10-08 20:20 UTC, jmzagowolox commented on src/test/java/training/article/create.feature
> +    And match response.article.author.username contains username
when you compare 2 strings, you must use `==`

2020-10-08 20:20 UTC, jmzagowolox commented on src/test/java/training/article/create.feature
> +    And match response.article.author.username contains username
and use assert

2020-10-08 20:20 UTC, jmzagowolox commented on src/test/java/training/article/article.feature
> +    * def updateArticle = call read('update.feature@flow')
add a space line and send the data of the created article to the update feature.

2020-10-08 20:25 UTC, jmzagowolox requested changes

2020-10-08 20:25 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    And match response.article.author.username contains username
use assert and `==` with strings

2020-10-09 12:30 UTC, Elvis-Mieles commented
## summary

Processes are optimized in the Article feature

2020-10-09 13:26 UTC, jmzagowolox requested changes

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/create.feature
> +    * def getArticle = call read('getArticle.feature@getArticle'){ passedSlug: '#(slug)' }
And getArticle = call read(dasdsd){ passedSlug: '#(response.article.slug)' }

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/getAll.feature
> +
add a space line at the end of the file

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def getArticle = call read('getArticle.feature@getArticle'){ passedSlug: '#(slug)' }
the same of create feature

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def randomArticle = function(articles) { return articles[Math.floor(Math.random() * articles.length)] }
you are repeating this function in some features. Please put this logic on a common file.

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def randomArticle = function(articles) { return articles[Math.floor(Math.random() * articles.length)] }
you can create a package `helpers` and put in them this function.

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def getArticles = call read('getAll.feature@getArticles')
check that logic is doing innecessary on e2e feature.

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/getArticle.feature
> +    Then status 200
do the validations for this endpoint (schema and slug)

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/create.feature
> +    * def token = "Bearer " + login.response.user.token
think about this. This steps are in ALL the features. Look at the hooks section in karate documentation and try to don't repeate this code :)

2020-10-09 13:26 UTC, jmzagowolox commented on src/test/java/training/article/GetAll.java
> +    }
you don't need to create a class for every feature you create.

2020-10-10 22:19 UTC, Elvis-Mieles commented
##summary
The login is added as an environment variable

2020-10-13 14:25 UTC, jmzagowolox requested changes

2020-10-13 14:25 UTC, jmzagowolox commented on src/test/java/training/helpers/Random.js
> +function getRandomInt(articles) {
change the name of `articles` to another because you can reuse this function for users, tags, comments, whatever, and it's not necessary for articles

2020-10-13 14:25 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def getArticle = call read('getArticle.feature@getArticle'){ passedSlug: '#(slug)' }
remember this!

2020-10-13 14:25 UTC, jmzagowolox commented on src/test/java/training/article/getArticle.feature
> +    Then status 200
remember this!

2020-10-13 14:25 UTC, jmzagowolox commented on src/test/java/training/article/getArticle.feature
> +    * def slug = typeof passedSlug == 'undefined' ? randomArticle(getArticles.response.articles).slug : passedSlug
you don't need to do this. Remember that you always called this scenario with a specific article.

2020-10-13 14:25 UTC, jmzagowolox commented on src/test/java/training/article/getArticle.feature
> +    Then status 200
do the validations for this endpoint (schema and slug)

2020-10-13 14:25 UTC, jmzagowolox commented on src/test/java/karate-config.js
> +}
please add a space line

2020-10-13 14:25 UTC, jmzagowolox commented on src/test/java/training/article/GetArticle.java
> +}
remember you don't need to create a runner for every feature

2020-10-13 14:27 UTC, jmzagowolox commented on src/test/java/karate-config.js
> +  var config = properties[env]
don't forget the `;` at the end of the line

2020-10-13 15:12 UTC, Elvis-Mieles commented
##summary
The previous PR corrections are made

2020-10-13 15:23 UTC, jmzagowolox requested changes

2020-10-13 15:23 UTC, jmzagowolox commented on src/test/java/training/article/getArticle.feature
> +    And match  response == responseGetArticles
add an space line at the end of the file, and you can check if the `articlesCount` is the same of the array (`articles`) length.

2020-10-13 15:23 UTC, jmzagowolox commented on src/test/java/training/article/responsearticles.json
> +  ],
this is exactly the same of the other json. I recommend you check if this `articles` is an array and after that check if every item of it is an article (that you defined in `responsesuccessfully.json`)

2020-10-13 15:23 UTC, jmzagowolox commented on src/test/java/training/article/responsesuccessfully.json
> +}
check the name of the file. Do you think the name of the file define this content ?

2020-10-13 15:23 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def getArticle = call read('getArticle.feature@getArticle'){ passedSlug: '#(slug)' }
remember this!!

2020-10-13 15:23 UTC, jmzagowolox commented on src/test/java/training/article/update.feature
> +    * def slug = typeof passedSlug == 'undefined' ? randomArticle(getArticles.response.articles).slug : passedSlug
remember, if you passed a slug, you don't need to `call` the scenario getAllArticles

2020-10-13 16:54 UTC, Elvis-Mieles commented
##summary
The name of the jsons and the content responsearticles.json are modified

2020-10-13 17:50 UTC, jmzagowolox requested changes

2020-10-13 17:50 UTC, jmzagowolox commented on src/test/java/training/article/responsearticle.json
> +    "tagList": [],
array of what? strings?

2020-10-13 17:50 UTC, jmzagowolox commented on src/test/java/karate-config.js
> +  config.token = "Bearer " + login.response.user.token
don't forget the ; at the end of the line

2020-10-13 19:26 UTC, Elvis-Mieles commented
##summary 
Changes are added to json and karate-config

2020-10-13 20:02 UTC, Elvis-Mieles commented
## summary 
The karate-config file is modified

2020-10-13 20:09 UTC, jmzagowolox approved these changes

2020-10-13 20:11 UTC, merged