The card profile is performed
wolox-training/em-karate pull request #6
Opened 2020-10-13 21:05 UTC by Elvis-Mieles

##summary
The card profile is performed

2020-10-13 21:18 UTC, jmzagowolox requested changes

2020-10-13 21:18 UTC, jmzagowolox commented on src/test/java/training/profile/updateprofile.feature
> +  Scenario Outline:  Update profile
if you only gonna do an example, don't use outline scenarios

2020-10-13 21:18 UTC, jmzagowolox commented on src/test/java/training/profile/updateprofile.feature
> +    |migueyliuiyles  |migueeysiuihf@gmail.com   |soy estudiante|imagen.png         |200       |
can you change every fields? is there any other validation to do?

2020-10-13 21:18 UTC, jmzagowolox commented on src/test/java/training/profile/getprofile.feature
> +    And match  response == responseGet
must the token match with the value on vaariable (`token`)?

2020-10-13 21:18 UTC, jmzagowolox commented on src/test/java/training/profile/schemegetprofile.json
> +    "image": "##Sstring",
check this typo

2020-10-13 21:18 UTC, jmzagowolox commented on src/test/java/training/profile/updateprofile.feature
> +    And assert getProfile.response.user.username === response.user.'<username>'
is that ok? is it work? why do you do that?

2020-10-13 21:18 UTC, jmzagowolox commented on src/test/java/training/profile/schemegetprofile.json
> +{
remember the name of the schemAs must be representative

2020-10-14 12:40 UTC, Elvis-Mieles commented
##summary
The @unitTest scenario has been added in the updateprofile feature

2020-10-14 13:19 UTC, jmzagowolox requested changes

2020-10-14 13:19 UTC, jmzagowolox commented on src/test/java/training/profile/updateprofile.feature
> +    And match  response == profileIncorrect
you always match with the schema what contains the "username" attribute, but you have an example where the email is incorrect. Is that error returned inside the username attribute?

2020-10-14 13:43 UTC, Elvis-Mieles commented
##summary
The wrong user schema.json file is modified

2020-10-14 14:44 UTC, jmzagowolox requested changes

2020-10-14 14:44 UTC, jmzagowolox commented on src/test/java/training/profile/userincorrectschema.json
> +      "##string"
"#string": "#[] #string"

2020-10-14 14:44 UTC, jmzagowolox commented on src/test/java/training/profile/userscheme.json
> +{
the correct word is SCHEMA

2020-10-14 15:21 UTC, Elvis-Mieles commented
##summary
The wrong userschema.json file is modified

2020-10-14 15:23 UTC, jmzagowolox approved these changes

2020-10-14 15:24 UTC, merged